/*
 * SmartBundleFIlterPanel.java
 *
 * Created on March 8, 2008, 6:50 PM
 */

package com.davidecavestro.rbe.gui;

/**
 *
 * Pannello contenente la checkbox per l'abilitazione del riconoscimento automatico dei bundle.
 *
 * @author  Davide Cavestro
 */
public class SmartBundleFIlterPanel extends javax.swing.JPanel {
	
	/** Creates new form SmartBundleFIlterPanel */
	public SmartBundleFIlterPanel (final boolean enableDetection) {
		initComponents ();
		jCheckBox1.getModel ().setSelected (enableDetection);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCheckBox1 = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        jCheckBox1.setFont(new java.awt.Font("Dialog", 0, 12));
        org.openide.awt.Mnemonics.setLocalizedText(jCheckBox1, java.util.ResourceBundle.getBundle("com.davidecavestro.timekeeper.gui.res").getString("FIleChooser/SmartBundleFilter/CheckBox"));
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jCheckBox1, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables

	public boolean isDetectionEnabled () {
		return jCheckBox1.getModel ().isSelected ();
	}
}
