/*
 * PresentationPanel.java
 *
 * Created on 28 gennaio 2006, 11.26
 */

package com.davidecavestro.rbe.gui;

import com.davidecavestro.common.application.ApplicationData;

/**
 *
 * @author  davide
 */
public class PresentationPanel extends javax.swing.JPanel {
	
	final ApplicationData _appData;
		
	/**
	 * Costruttore.
	 * @param appData i dati applicativi.
	 */
	public PresentationPanel (ApplicationData appData) {
		_appData = appData;
		initComponents ();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        appVersionLabel = new javax.swing.JLabel();
        applicationImageLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        appNameLabel.setFont(new java.awt.Font("Impact", 1, 60));
        appNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        appNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(appNameLabel, _appData.getApplicationExternalName ());
        appNameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        appNameLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(appNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 210, 100));

        appVersionLabel.setFont(new java.awt.Font("Impact", 1, 28));
        appVersionLabel.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(appVersionLabel, _appData.getVersionNumber ());
        appVersionLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        appVersionLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(appVersionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 34, 100, 60));

        applicationImageLabel.setForeground(new java.awt.Color(255, 255, 255));
        applicationImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/davidecavestro/rbe/gui/images/splash.png")));
        applicationImageLabel.setIconTextGap(-300);
        jPanel1.add(applicationImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JLabel appVersionLabel;
    private javax.swing.JLabel applicationImageLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
	
	/**
	 * Imposta il testo dell'etichetta centrale per le informazioni.
	 *
	 * @param info il testo da mostrare.
	 */	
	public void setInfoText (final String info){
		applicationImageLabel.setText (info);
	}
}
